defmodule Swift4Shop.Cart.Reduced do
  @derive Jason.Encoder
  defstruct CustomerId: nil,
            BillingFirstName: "",
            BillingLastName: "",
            BillingCompany: "",
            BillingAddress: "",
            BillingAddress2: "",
            BillingCity: "",
            BillingState: "",
            BillingZipCode: "",
            BillingCountry: "",
            BillingPhoneNumber: "",
            BillingEmail: "",
            ShipmentFirstName: "",
            ShipmentLastName: "",
            ShipmentCompany: "",
            ShipmentAddress: "",
            ShipmentAddress2: "",
            ShipmentCity: "",
            ShipmentState: "",
            ShipmentZipCode: "",
            ShipmentCountry: "",
            ShipmentPhone: "",
            ShipmentEmail: ""
end
