defmodule Shift4Shop.Crm.Distributor do
  @derive Jason.Encoder
  defstruct DistributorID: nil,
            CompanyName: "",
            ContactName: "",
            Address: "",
            Address2: "",
            City: "",
            State: "",
            Zip: "",
            Country: "",
            Phone: "",
            Fax: "",
            Email: "",
            Comments: "",
            NotifyOnNewOrder: "",
            NotifyOnNewOrderEmailSubject: "",
            NotifyOnNewOrderEmailMessage: "",
            UserID: "",
            LastUpdate: "",
            IsDropShipper: "",
            NotifyOnCancelledOrder: "",
            NotifyOnCancelledOrderEmailSubject: "",
            NotifyOnCancelledOrderEmailMessage: "",
            POStyle: nil,
            POEmailNotification: nil,
            POShippingInfo: "",
            POPaymentInfo: "",
            POAdditionalNotes: "",
            POEmailSubject: ""
end
