defmodule Shift4Shop.Order.Item do
  @derive Jason.Encoder
  defstruct CatalogID: nil,
            ItemIndexID: nil,
            ItemID: nil,
            ItemShipmentID: nil,
            ItemQuantity: nil,
            ItemWarehouseID: nil,
            ItemDescription: nil,
            ItemUnitPrice: nil,
            ItemWeight: nil,
            ItemOptionPrice: nil,
            ItemAdditionalField1: nil,
            ItemAdditionalField2: nil,
            ItemAdditionalField3: nil,
            ItemPageAdded: nil,
            ItemAvailability: nil,
            ItemDateAdded: nil,
            ItemUnitCost: nil,
            ItemUnitStock: nil,
            ItemOptions: nil,
            ItemCatalogIDOptions: nil,
            ItemSerial: nil,
            ItemImage1: nil,
            ItemImage2: nil,
            ItemImage3: nil,
            ItemImage4: nil,
            ItemWarehouseLocation: nil,
            ItemWarehouseBin: nil,
            ItemWarehouseAisle: nil,
            ItemWarehouseCustom: nil,
            RecurringOrderFrequency: nil
end
