defmodule Shift4Shop.Promotions do
  @derive Jason.Encoder
  defstruct PromotionID: 1,
            PromotionName: "sample string strCount",
            PromotionDescription: "sample string strCount",
            PromotionStart: "sample string strCount",
            PromotionEnd: "sample string strCount",
            PromotionEnabled: 1,
            PromotionByAmount: 1,
            PromotionCheckByAmount: 1,
            PromotionByQuantity: 1,
            PromotionCheckByQuantity: 1,
            PromotionByProduct: 1,
            PromotionByCategory: "sample string strCount",
            PromotionAmount: 1.1,
            PromotionPercentage: 1,
            PromotionPerItem: 1,
            PromotionCategory: "sample string strCount",
            PromotionProduct: "sample string strCount",
            PromotionFreeShipping: 1,
            PromotionFreeProduct: "sample string strCount",
            PromotionProduct1ID: 1,
            PromotionProduct1Quantity: 1,
            PromotionProduct2ID: 1,
            PromotionProduct2Quantity: 1,
            PromotionProduct3ID: 1,
            PromotionProduct3Quantity: 1,
            PromotionProductID: 1,
            PromotionProduct4Quantity: 1,
            PromotionCoupon: "sample string strCount",
            PromotionUses: 1,
            PromotionMaxUses: 1,
            PromotionUsesPerCustomer: 1,
            PromotionGroupID: "sample string strCount",
            PromotionUserid: "sample string strCount",
            PromotionLastUpdate: "sample string strCount",
            PromotionByAmount2: 1.1,
            PromotionByQuantity2: 1.1,
            PromotionCountry: "sample string strCount",
            PromotionState: "sample string strCount",
            PromotionNonStackable: 1,
            PromotionRulesRetailPrice: 1,
            PromotionExcludeManufacturers: "sample string strCount",
            PromotionFreeProductPrice: 1.1,
            PromotionExcludePreorder: 1,
            PromotionExcludeSpecialOrder: 1,
            PromotionShippingDiscount: 1.1,
            PromotionShippingOptions: "sample string strCount",
            PromotionRecurringOrders: 1,
            PromotionBonusRewardPoints: 1
end
