defmodule Swift4Shop.Shipment do
  @derive Jason.Encoder
  defstruct ShipmentID: nil,
            ShipmentLastUpdate: "",
            ShipmentBoxes: nil,
            ShipmentInternalComment: "",
            ShipmentOrderStatus: nil,
            ShipmentAddress: "",
            ShipmentAddress2: "",
            ShipmentAlias: "",
            ShipmentCity: "",
            ShipmentCompany: "",
            ShipmentCost: nil,
            ShipmentCountry: "",
            ShipmentEmail: "",
            ShipmentFirstName: "",
            ShipmentLastName: "",
            ShipmentMethodID: nil,
            ShipmentMethodName: "",
            ShipmentShippedDate: "",
            ShipmentPhone: "",
            ShipmentState: "",
            ShipmentZipCode: "",
            ShipmentTax: nil,
            ShipmentWeight: nil,
            ShipmentTrackingCode: "",
            ShipmentUserID: "",
            ShipmentNumber: nil,
            ShipmentAddressTypeID: nil
end
